# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build Server
      # -B means 'batch mode' (i.e. without colored output etc.)
      run: mvn package -P BuildServer -B
    - name: Build Client
      run: mvn package -P BuildClient -B
    - name: Upload jars
      uses: actions/upload-artifact@v2
      with:
        name: 'jar'
        path: target/*.jar
    - name: Invoke Server HTTP API
      run: curl 18.195.117.7:8000/updateGameServer

