# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build Server
      # -B means 'batch mode' (i.e. without colored output etc.)
      run: mvn package -P BuildServer -B
    - name: Build Client
      run: mvn package -P BuildClient -B

      # create a directory, then move server and client jars to there
    - name: Move jars
      run: |
        mkdir upload-jars
        cp target/server*.jar upload-jars/
        cp target/client*.jar upload-jars/
    - name: Upload jars
      uses: actions/upload-artifact@v2
      with:
        name: 'jar'
        path: upload-jars

    # Update tag and pre-release
    # - Update (force-push) tag to the commit that is used in the workflow.
    # - Upload artifacts defined by the user.
    - uses: eine/tip@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: tip # create release at git tag 'tip'
        rm: true # remove previous artifacts
        files: |
          target/server*.jar
          target/client*.jar

  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Invoke Server HTTP API
      # save the response, print the response, and check if response is "game server updated"
      run: |
        result=$(curl 18.195.117.7:8000/updateGameServer)
        echo output: ${result}
        [[ "${result}" = 'will check later' ]] || [[ "${result}" = 'game server updated' ]]